<?php
require_once __DIR__ . '/bootstrap.php'; $u=require_login(); $pdo=db();
$q=trim($_GET['q']??''); $state=$_GET['state']??''; $year=$_GET['year']??'';
$where=[];$args=[];
if($q!==''){ $where[]="(p.project_code LIKE ? OR p.project_name LIKE ? OR i.code LIKE ? OR i.name LIKE ? OR s.country LIKE ?)"; for($i=0;$i<5;$i++)$args[]="%$q%"; }
if(in_array($state,['draft','review','approval','approved'],true)){ $where[]="s.state=?";$args[]=$state; }
if(ctype_digit((string)$year)){ $where[]="s.reporting_year=?";$args[]=(int)$year; }
$sql="SELECT s.*,p.project_code,p.project_name,i.code indicator_code,i.name indicator_name,u.name submitter FROM submissions s JOIN projects p ON p.id=s.project_id JOIN indicators i ON i.id=s.indicator_id JOIN users u ON u.id=s.submitted_by ".($where?'WHERE '.implode(' AND ',$where):'')." ORDER BY s.updated_at DESC";
$st=$pdo->prepare($sql);$st->execute($args);$rows=$st->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Submissions | ISLANDS</title><link rel="stylesheet" href="assets/app.css"></head><body><div class="app-shell"><?php include __DIR__.'/partials/sidebar.php'; ?><main class="main"><header class="topbar"><div><div class="eyebrow">DATA MANAGEMENT</div><h1>GEB submissions</h1><p class="muted">Search, review and manage programme monitoring records.</p></div><a class="btn primary" href="submission.php">+ New submission</a></header>
<section class="panel"><div class="panel-head"><div><div class="eyebrow">DATA EXPORT</div><h3>Export reporting data</h3><p class="muted">Exports respect the search, status and year filters below.</p></div><div class="top-actions"><a class="btn secondary" href="export.php?format=csv&amp;q=<?=urlencode($q)?>&amp;state=<?=urlencode($state)?>&amp;year=<?=urlencode($year)?>">↓ CSV</a><a class="btn primary" href="export.php?format=xlsx&amp;q=<?=urlencode($q)?>&amp;state=<?=urlencode($state)?>&amp;year=<?=urlencode($year)?>">↓ Excel (.xlsx)</a></div></div><form class="filters"><div><label>Search<input name="q" value="<?=e($q)?>" placeholder="Project, indicator, country..."></label></div><div><label>Status<select name="state"><option value="">All statuses</option><?php foreach(['draft'=>'Draft','review'=>'Review','approval'=>'Approval','approved'=>'Completed'] as $k=>$v): ?><option value="<?=$k?>" <?=$state===$k?'selected':''?>><?=$v?></option><?php endforeach; ?></select></label></div><div><label>Year<input name="year" value="<?=e($year)?>" placeholder="2026"></label></div><button class="btn secondary" type="submit">Filter</button><a class="btn ghost" href="submissions.php">Reset</a></form>
<div class="table-wrap"><table class="wide"><thead><tr><th>ID</th><th>Project</th><th>Indicator</th><th>Country</th><th>Value</th><th>Year</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td>#<?=str_pad((string)$r['id'],5,'0',STR_PAD_LEFT)?></td><td><strong><?=e($r['project_code'])?></strong><small><?=e($r['project_name'])?></small></td><td><span class="code"><?=e($r['indicator_code'])?></span><small><?=e($r['indicator_name'])?></small></td><td><?=e($r['country'])?></td><td><strong><?=e(rtrim(rtrim(number_format((float)$r['reported_value'],4,'.',''),'0'),'.'))?></strong> <?=e($r['unit'])?></td><td><?=$r['reporting_year']?></td><td><span class="status <?=e($r['state'])?>"><?=e(workflow_label($r['state']))?></span></td><td><a class="btn small" href="submission.php?id=<?=$r['id']?>">Open</a></td></tr><?php endforeach; if(!$rows): ?><tr><td colspan="8" class="empty">No submissions match your filters.</td></tr><?php endif; ?></tbody></table></div></section></main></div></body></html>
