<?php
require_once __DIR__ . '/bootstrap.php';
$u=require_login();$pdo=db();$id=isset($_GET['id'])?(int)$_GET['id']:0;
$editing=$id>0;
$sub=null;
if($editing){$s=$pdo->prepare("SELECT s.*,p.project_code,p.project_name,p.region,i.code indicator_code,i.name indicator_name,i.level indicator_level,u.name submitter,r.name reviewer,r.email reviewer_email,a.name approver,a.email approver_email FROM submissions s JOIN projects p ON p.id=s.project_id JOIN indicators i ON i.id=s.indicator_id JOIN users u ON u.id=s.submitted_by LEFT JOIN users r ON r.id=s.reviewer_id LEFT JOIN users a ON a.id=s.approver_id WHERE s.id=?");$s->execute([$id]);$sub=$s->fetch();if(!$sub)exit('Submission not found.');}
$projects=$pdo->query("SELECT * FROM projects WHERE active=1 ORDER BY project_code")->fetchAll();
$indicators=$pdo->query("SELECT * FROM indicators WHERE active=1 ORDER BY code")->fetchAll();
$users=$pdo->query("SELECT id,name,email,role,organization FROM users WHERE active=1 ORDER BY name")->fetchAll();
$beneficiaryCategories=$pdo->query("SELECT * FROM geb_beneficiary_categories ORDER BY sort_order")->fetchAll();
$beneficiaryExisting=[]; $policyExisting=[];
if($editing){$x=$pdo->prepare("SELECT * FROM geb_beneficiary_reports WHERE submission_id=?");$x->execute([$id]);foreach($x->fetchAll() as $r)$beneficiaryExisting[$r['category_id']]=$r; $x=$pdo->prepare("SELECT * FROM geb_policy_instruments WHERE submission_id=?");$x->execute([$id]);foreach($x->fetchAll() as $r)$policyExisting[$r['category_code']]=$r;}
$policyCategories=[
 ['a','Legal framework and/or import-related regulations aimed at preventing and/or controlling the import of hazardous chemicals, products containing hazardous chemicals, or products that result in hazardous waste'],
 ['b','National/regional chemical classification and labelling standards (including GHS-aligned standards) to track and control import'],
 ['c','Specific policy instruments aimed at reducing the demand for imported hazardous chemicals and products that result in hazardous waste (procurement criteria, sectoral partnerships or standards)']
];
$flashes=get_flashes();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'save';
 $pid=(int)($_POST['project_id']??0);$year=(int)($_POST['reporting_year']??0);$iid=(int)($_POST['indicator_id']??0);
 $indicatorCode=(string)$pdo->query("SELECT code FROM indicators WHERE id=".$iid)->fetchColumn();
 $maleInput=$_POST['male']??[]; $femaleInput=$_POST['female']??[]; $policyStage=$_POST['policy_stage']??[]; $policyDescription=$_POST['policy_description']??[];$country=trim($_POST['country']??'');$value=(float)($_POST['reported_value']??0);
 if($indicatorCode==='GEF #11'){ $value=0; foreach($beneficiaryCategories as $bc){$cid=(int)$bc['id'];$m=max(0,(int)($maleInput[$cid]??0));$f=max(0,(int)($femaleInput[$cid]??0));$value += $m+$f;} }$unit=trim($_POST['unit']??'');$dis=trim($_POST['disaggregation']??'');$source=trim($_POST['data_source']??'');$method=trim($_POST['methodology']??'');$notes=trim($_POST['notes']??'');$reviewer=(int)($_POST['reviewer_id']??0)?:null;$approver=(int)($_POST['approver_id']??0)?:null;
 if(!$pid||!$year||!$iid||$country===''||$unit===''||$source===''||$method==='')$errors[]='Complete all required fields before saving.';
 if($value<0)$errors[]='Reported value cannot be negative.';
 if(!$errors){
  if(!$editing){
   $s=$pdo->prepare("INSERT INTO submissions(project_id,reporting_year,indicator_id,country,reported_value,unit,disaggregation,data_source,methodology,notes,state,submitted_by,reviewer_id,approver_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'draft',?,?,?,NOW(),NOW())");
   $s->execute([$pid,$year,$iid,$country,$value,$unit,$dis,$source,$method,$notes,$u['id'],$reviewer,$approver]);$id=(int)$pdo->lastInsertId();audit($id,$u['id'],'Created','', 'draft','Submission created.');
   if($indicatorCode==='GEF #11'){ save_beneficiary_breakdown($id,$beneficiaryCategories,$maleInput,$femaleInput,$pdo); sync_geb11_derived_records($id); }
   if($indicatorCode==='GEF #10.1'){ save_policy_instruments($id,$policyCategories,$policyStage,$policyDescription,$pdo); }
   $fresh=$pdo->prepare("SELECT s.*,p.project_code,i.code indicator_code,r.name reviewer_name,r.email reviewer_email,a.name approver_name,a.email approver_email FROM submissions s JOIN projects p ON p.id=s.project_id JOIN indicators i ON i.id=s.indicator_id LEFT JOIN users r ON r.id=s.reviewer_id LEFT JOIN users a ON a.id=s.approver_id WHERE s.id=?");$fresh->execute([$id]);$assigned=$fresh->fetch();
   if($assigned){ if($reviewer){ notify_assignment($assigned,'reviewer',$assigned['reviewer_email']??null); } if($approver){ notify_assignment($assigned,'approver',$assigned['approver_email']??null); } }
   flash('success','Submission saved as Draft.');redirect('submission.php?id='.$id);
  } else {
   $oldReviewer = $sub['reviewer_id'] ?? null; $oldApprover = $sub['approver_id'] ?? null;
   $s=$pdo->prepare("UPDATE submissions SET project_id=?,reporting_year=?,indicator_id=?,country=?,reported_value=?,unit=?,disaggregation=?,data_source=?,methodology=?,notes=?,reviewer_id=?,approver_id=?,updated_at=NOW() WHERE id=?");$s->execute([$pid,$year,$iid,$country,$value,$unit,$dis,$source,$method,$notes,$reviewer,$approver,$id]);
   if($indicatorCode==='GEF #11'){ save_beneficiary_breakdown($id,$beneficiaryCategories,$maleInput,$femaleInput,$pdo); sync_geb11_derived_records($id); }
   if($indicatorCode==='GEF #10.1'){ save_policy_instruments($id,$policyCategories,$policyStage,$policyDescription,$pdo); }
   $fresh=$pdo->prepare("SELECT s.*,p.project_code,i.code indicator_code,r.name reviewer_name,r.email reviewer_email,a.name approver_name,a.email approver_email FROM submissions s JOIN projects p ON p.id=s.project_id JOIN indicators i ON i.id=s.indicator_id LEFT JOIN users r ON r.id=s.reviewer_id LEFT JOIN users a ON a.id=s.approver_id WHERE s.id=?");$fresh->execute([$id]);$assigned=$fresh->fetch();
   if($assigned && (string)$reviewer !== (string)$oldReviewer && $reviewer){ notify_assignment($assigned,'reviewer',$assigned['reviewer_email']??null); }
   if($assigned && (string)$approver !== (string)$oldApprover && $approver){ notify_assignment($assigned,'approver',$assigned['approver_email']??null); }
   flash('success','Submission details updated.');redirect('submission.php?id='.$id);
  }
 }
}
if($editing){$s=$pdo->prepare("SELECT s.*,p.project_code,p.project_name,p.region,i.code indicator_code,i.name indicator_name,i.level indicator_level,u.name submitter,r.name reviewer,r.email reviewer_email,a.name approver,a.email approver_email FROM submissions s JOIN projects p ON p.id=s.project_id JOIN indicators i ON i.id=s.indicator_id JOIN users u ON u.id=s.submitted_by LEFT JOIN users r ON r.id=s.reviewer_id LEFT JOIN users a ON a.id=s.approver_id WHERE s.id=?");$s->execute([$id]);$sub=$s->fetch();}
$events=$editing?$pdo->prepare("SELECT e.*,u.name FROM workflow_events e LEFT JOIN users u ON u.id=e.user_id WHERE e.submission_id=? ORDER BY e.created_at DESC"):null;if($events){$events->execute([$id]);$events=$events->fetchAll();}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $editing?'Submission #'.str_pad((string)$id,5,'0',STR_PAD_LEFT):'New submission'?> | ISLANDS</title><link rel="stylesheet" href="assets/app.css"></head><body><div class="app-shell"><?php include __DIR__.'/partials/sidebar.php'; ?><main class="main">
<header class="topbar"><div><div class="eyebrow"><?= $editing?'SUBMISSION RECORD':'NEW RECORD'?></div><h1><?= $editing?'GEB submission #'.str_pad((string)$id,5,'0',STR_PAD_LEFT):'Create GEB submission'?></h1><p class="muted"><?= $editing?'Update evidence, assignments and workflow status.':'Capture a verified programme result for review.'?></p></div><?php if($editing): ?><span class="status large <?=$sub['state']?>"><?=e(workflow_label($sub['state']))?></span><?php endif; ?></header>
<?php foreach($flashes as $f): ?><div class="alert <?=e($f[0])?>"><?=e($f[1])?></div><?php endforeach; ?><?php foreach($errors as $er): ?><div class="alert danger"><?=e($er)?></div><?php endforeach; ?>
<?php if($editing): ?><section class="workflow-panel"><div class="workflow-head"><div><div class="eyebrow">WORKFLOW</div><h3>Submission lifecycle</h3></div><div class="workflow-note">Every action is recorded in the audit trail.</div></div><div class="workflow"><div class="wf-step <?=in_array($sub['state'],['review','approval','approved'],true)?'done':($sub['state']==='draft'?'current':'')?>"><span>1</span><strong>Draft</strong><small>Data capture</small></div><i class="<?=in_array($sub['state'],['review','approval','approved'],true)?'done':''?>"></i><div class="wf-step <?=$sub['state']==='review'?'current':(in_array($sub['state'],['approval','approved'],true)?'done':'')?>"><span>2</span><strong>Review</strong><small>Quality assurance</small></div><i class="<?=in_array($sub['state'],['approval','approved'],true)?'done':''?>"></i><div class="wf-step <?=$sub['state']==='approval'?'current':($sub['state']==='approved'?'done':'')?>"><span>3</span><strong>Approval</strong><small>Final verification</small></div><i class="<?=$sub['state']==='approved'?'done':''?>"></i><div class="wf-step <?=$sub['state']==='approved'?'current':''?>"><span>4</span><strong>Completed</strong><small>Final record</small></div></div>
<div class="workflow-actions">
<?php
$workflowTargets = [
    'draft' => ['label'=>'Move to Draft','class'=>'secondary'],
    'review' => ['label'=>'Move to Review','class'=>'primary'],
    'approval' => ['label'=>'Move to Approval','class'=>'secondary'],
    'approved' => ['label'=>'Move to Completed','class'=>'success'],
];
foreach ($workflowTargets as $target => $meta):
    if ($target === $sub['state']) continue;
?>
<form method="POST" action="workflow_action.php">
    <input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
    <input type="hidden" name="action" value="move_to">
    <input type="hidden" name="target_state" value="<?=e($target)?>">
    <input type="hidden" name="submission_id" value="<?=$id?>">
    <button type="submit" class="btn <?=$meta['class']?>"><?=$meta['label']?></button>
</form>
<?php endforeach; ?>
</div></section><?php endif; ?>
<form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>">
<div class="form-layout"><div>
<section class="panel form-section"><div class="section-title"><span>01</span><div><div class="eyebrow">IDENTIFICATION</div><h3>Project information</h3></div></div><div class="form-grid"><label>Child project*<select name="project_id" required><option value="">Select project</option><?php foreach($projects as $p): ?><option value="<?=$p['id']?>" <?=($sub['project_id']??0)==$p['id']?'selected':''?>><?=e($p['project_code'].' — '.$p['project_name'])?></option><?php endforeach; ?></select></label><label>Reporting year*<input type="number" name="reporting_year" min="2000" max="2100" value="<?=e((string)($sub['reporting_year']??date('Y')))?>" required></label><label>Country*<input name="country" value="<?=e($sub['country']??'')?>" placeholder="Country of reporting" required></label></div></section>
<section class="panel form-section"><div class="section-title"><span>02</span><div><div class="eyebrow">MEASUREMENT</div><h3>GEB indicator</h3></div></div><label>Indicator*<select name="indicator_id" required><option value="">Select indicator</option><?php foreach($indicators as $i): ?><option value="<?=$i['id']?>" <?=($sub['indicator_id']??0)==$i['id']?'selected':''?>><?=e($i['code'].' — '.$i['name'])?></option><?php endforeach; ?></select></label><div class="form-grid"><label>Reported value*<input type="number" step="any" min="0" name="reported_value" value="<?=e((string)($sub['reported_value']??''))?>" placeholder="0.00" required></label><label>Unit*<input name="unit" value="<?=e($sub['unit']??'')?>" placeholder="e.g. metric tonnes, people" required></label></div><label>Disaggregation / details<textarea name="disaggregation" rows="4" placeholder="Sex, age, geography, technology or other relevant disaggregation."><?=e($sub['disaggregation']??'')?></textarea></label>
<div id="beneficiary-panel" class="special-indicator-panel" hidden><div class="special-head"><div><div class="eyebrow">GEF #11 BENEFICIARY CATEGORIES</div><h4>People benefiting from GEF-financed investments</h4><p>Enter male and female beneficiaries by the seven role-based categories. The portal sums these values into GEF #11 and derives GEF #11.1 (male) and GEF #11.2 (female).</p></div><strong id="beneficiary-total">Total: 0</strong></div><div class="table-wrap"><table class="wide"><thead><tr><th>Category</th><th>Definition</th><th>Examples</th><th>Male</th><th>Female</th><th>Total</th></tr></thead><tbody><?php foreach($beneficiaryCategories as $bc):$br=$beneficiaryExisting[$bc['id']]??[];?><tr><td><strong><?=e($bc['category_no'].'. '.$bc['name'])?></strong><input type="hidden" name="beneficiary_category_id[]" value="<?=$bc['id']?>"></td><td><?=e($bc['definition'])?></td><td><?=e($bc['examples'])?></td><td><input class="beneficiary-count male-count" data-category="<?=$bc['id']?>" type="number" min="0" step="1" name="male[<?=$bc['id']?>]" value="<?=e((string)($br['male_count']??0))?>"></td><td><input class="beneficiary-count female-count" data-category="<?=$bc['id']?>" type="number" min="0" step="1" name="female[<?=$bc['id']?>]" value="<?=e((string)($br['female_count']??0))?>"></td><td class="row-total" data-category="<?=$bc['id']?>">0</td></tr><?php endforeach;?></tbody></table></div></div>
<div id="policy-panel" class="special-indicator-panel" hidden><div class="special-head"><div><div class="eyebrow">GEF #10.1 POLICY / REGULATORY INSTRUMENTS</div><h4>Countries with legislation/policy to control emissions of POPs to air</h4><p>Select the instrument category and the stage of advancement. Add a short description of the project-supported policy or instrument.</p></div></div><div class="table-wrap"><table class="wide"><thead><tr><th>Policy / instrument category</th><th>Stage of advancement</th><th>Description / instrument produced</th></tr></thead><tbody><?php foreach($policyCategories as [$pc,$pn]):$pr=$policyExisting[$pc]??[];?><tr><td><strong><?=e($pc.') '.$pn)?></strong></td><td><select name="policy_stage[<?=$pc?>]"><option value="">Not reported</option><?php foreach(['consultation'=>'In consultation','drafted'=>'Drafted','adopted'=>'Adopted','under_implementation'=>'Under implementation'] as $sk=>$sv):?><option value="<?=$sk?>" <?=($pr['advancement_stage']??'')===$sk?'selected':''?>><?=$sv?></option><?php endforeach;?></select></td><td><textarea name="policy_description[<?=$pc?>]" rows="3"><?=e($pr['description']??'')?></textarea></td></tr><?php endforeach;?></tbody></table></div></div></section>
<section class="panel form-section"><div class="section-title"><span>03</span><div><div class="eyebrow">EVIDENCE</div><h3>Source & methodology</h3></div></div><label>Data source*<textarea name="data_source" rows="3" required placeholder="Identify the source documents, systems or records."><?=e($sub['data_source']??'')?></textarea></label><label>Calculation methodology*<textarea name="methodology" rows="4" required placeholder="Explain how the reported value was calculated or verified."><?=e($sub['methodology']??'')?></textarea></label><label>Notes<textarea name="notes" rows="3" placeholder="Additional context, caveats or reviewer notes."><?=e($sub['notes']??'')?></textarea></label><div class="upload-box"><strong>Supporting evidence</strong><span>PDF, Word, Excel or image files can be attached in the next production configuration.</span></div></section>
</div><aside>
<section class="panel side-panel"><div class="section-title compact"><span>04</span><div><div class="eyebrow">GOVERNANCE</div><h3>Assignment</h3></div></div><label>Reviewer<select name="reviewer_id"><option value="">Select reviewer</option><?php foreach($users as $x): ?><option value="<?=$x['id']?>" <?=($sub['reviewer_id']??0)==$x['id']?'selected':''?>><?=e($x['name'].' — '.$x['role'])?></option><?php endforeach; ?></select></label><label>Approver<select name="approver_id"><option value="">Select approver</option><?php foreach($users as $x): ?><option value="<?=$x['id']?>" <?=($sub['approver_id']??0)==$x['id']?'selected':''?>><?=e($x['name'].' — '.$x['role'])?></option><?php endforeach; ?></select></label><?php if($editing): ?><div class="assignment"><div><span>REVIEWER</span><strong><?=e($sub['reviewer']??'Not assigned')?></strong><small><?=e($sub['reviewer_email']??'')?></small></div><div><span>APPROVER</span><strong><?=e($sub['approver']??'Not assigned')?></strong><small><?=e($sub['approver_email']??'')?></small></div></div><?php endif; ?></section>
<section class="panel side-panel"><div class="eyebrow">RECORD INFORMATION</div><div class="meta-list"><div><span>Submitted by</span><strong><?=e($sub['submitter']??$u['name'])?></strong></div><div><span>State</span><strong><?=e(workflow_label($sub['state']??'draft'))?></strong></div><div><span>Last updated</span><strong><?=e($sub['updated_at']??'Not yet')?></strong></div></div></section>
</aside></div><div class="form-actions"><a class="btn ghost" href="submissions.php">Cancel</a><button class="btn primary" type="submit"><?= $editing?'Save changes':'Save as Draft'?></button></div></form>
<?php if($editing): ?><section class="panel audit"><div class="panel-head"><div><div class="eyebrow">AUDIT TRAIL</div><h3>Workflow history</h3></div></div><?php foreach($events as $ev): ?><div class="audit-row"><span class="audit-dot"></span><div><strong><?=e($ev['action'])?></strong><span><?=e($ev['name']??'System')?> · <?=e($ev['created_at'])?></span><?php if($ev['note']): ?><small><?=e($ev['note'])?></small><?php endif; ?></div><span class="audit-state"><?=e(workflow_label($ev['to_state']??''))?></span></div><?php endforeach; if(!$events): ?><div class="empty">No workflow events yet.</div><?php endif; ?></section><?php endif; ?>
<script>const IND_CODES=<?=json_encode(array_column($indicators,'code','id'),JSON_UNESCAPED_UNICODE)?>;const indSel=document.querySelector('select[name="indicator_id"]');const benPanel=document.getElementById('beneficiary-panel');const polPanel=document.getElementById('policy-panel');const totalEl=document.getElementById('beneficiary-total');function calcBen(){let total=0;document.querySelectorAll('.beneficiary-count').forEach(x=>{let v=Math.max(0,parseInt(x.value||0));x.value=v});document.querySelectorAll('tr[data-category]').forEach(()=>{});document.querySelectorAll('.row-total').forEach(cell=>{const id=cell.dataset.category;const m=parseInt(document.querySelector('.male-count[data-category="'+id+'"]').value||0);const f=parseInt(document.querySelector('.female-count[data-category="'+id+'"]').value||0);const t=m+f;cell.textContent=t;total+=t});totalEl.textContent='Total: '+total;const value=document.querySelector('input[name="reported_value"]');if(value) {value.value=total; value.readOnly=true;}}function toggleSpecial(){const code=IND_CODES[indSel.value]||'';benPanel.hidden=code!=='GEF #11';polPanel.hidden=code!=='GEF #10.1';const value=document.querySelector('input[name="reported_value"]');if(value){value.readOnly=code==='GEF #11';if(code==='GEF #11')calcBen();} }indSel.addEventListener('change',toggleSpecial);document.querySelectorAll('.beneficiary-count').forEach(x=>x.addEventListener('input',calcBen));toggleSpecial();</script></main></div></body></html>
